### ISSUE TITLE
i have a question when i run postinstall  Error: read ECONNRESET at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

### ISSUE THREAD

**Issue by hardyzp** [rchain/exchange-api-njs#38]
i want to know the lib/rnode-grpc-gen/js is must have to download by  https://raw.githubusercontent.com/scalapb/ScalaPB/master/protobuf/scalapb/scalapb.proto . if possible can you offer it to me.my english is not very wall。 I hope you can understand me

**Comment by zsluedem** [comment]
If you are behind a firewall , please use some proxies.

**Comment by hardyzp** [comment]
yes, i user Singapore server.in the end i finally solved it .

**Comment by zsluedem** [comment]
Feel free to open it if you still got some other questions on it.
