### ISSUE TITLE
i ask a quest that when i transfer rev and deploy by the testnet  .it will return a deployid Whether I have enough balance or not

### ISSUE THREAD

**Issue by hardyzp** [rchain/exchange-api-njs#39]
i want to kown how to whether it is a valid transaction。

**Comment by zsluedem** [comment]
You can find the deploy by the deployId through https://github.com/rchain/exchange-api-njs/blob/master/examples/grpc_api_example.js#L50. This api would give you the blockHash.
Then you can try to find the transaction by https://github.com/rchain/exchange-api-njs/blob/master/examples/transaction_example.js.

**Comment by zsluedem** [comment]
I am going to close this issue sinece there is no replies for more than one week. Feel free to open it again if you got more questions.
