### ISSUE TITLE
i have a question auout transfer what about the different of the  vault_example.js and transfer_sign.js

### ISSUE THREAD

**Issue by hardyzp** [rchain/exchange-api-njs#40]

**Comment by zsluedem** [comment]
They are functionally the same.

The difference is that transfer_sign.js is more focused on how to split the signing and submitting the request which would be required for higher security situation while vault_example.js provide a simple method to just transfer which hides the logics inside.

**Comment by zsluedem** [comment]
close this one since no replies for more than on week. Feel free to reopen it if you got futher questions.
